import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  try {
    const { analysisId } = await request.json()

    if (!analysisId) {
      return NextResponse.json({ error: 'Analysis ID required' }, { status: 400 })
    }

    const analysis = await prisma.analysisJob.findUnique({
      where: { id: analysisId },
      include: {
        rubric: { select: { title: true, researchGoals: true } },
      },
    })

    if (!analysis) {
      return NextResponse.json({ error: 'Analysis not found' }, { status: 404 })
    }

    const themes = (analysis.themes as any[]) || []
    const insights = (analysis.insights as any[]) || []
    const recommendations = (analysis.recommendations as any[]) || []

    let markdown = `# Research Analysis Report

## ${analysis.rubric.title}

**Generated:** ${analysis.completedAt?.toLocaleDateString() || 'N/A'}
**Interviews Analyzed:** ${analysis.interviewCount}
**Overall Confidence:** ${analysis.confidence || 0}%

---

## Research Goals

${analysis.rubric.researchGoals}

---

## Key Themes

`

    themes.forEach((theme, idx) => {
      markdown += `### ${idx + 1}. ${theme.name}

**Prevalence:** ${theme.prevalence}% | **Sentiment:** ${theme.sentiment || 'N/A'}

${theme.description}

`
      if (theme.supportingQuotes?.length > 0) {
        markdown += `**Supporting Quotes:**\n\n`
        theme.supportingQuotes.forEach((q: any) => {
          markdown += `> "${q.quote}"\n\n`
        })
      }
      markdown += `---\n\n`
    })

    markdown += `## Key Insights\n\n`
    insights.forEach((insight, idx) => {
      markdown += `### ${idx + 1}. ${insight.text}

- **Confidence:** ${insight.confidence}%
- **Supporting Interviews:** ${insight.supportingInterviewCount}

`
    })

    markdown += `---\n\n## Recommendations\n\n`
    recommendations.forEach((rec, idx) => {
      const priorityIndicator = rec.priority === 'high' ? '[HIGH]' : rec.priority === 'medium' ? '[MEDIUM]' : '[LOW]'
      markdown += `### ${idx + 1}. ${rec.text}

${priorityIndicator} **Priority:** ${rec.priority.toUpperCase()}
${rec.impact ? `**Impact:** ${rec.impact}` : ''}

`
    })

    markdown += `\n---\n\n*Generated by Resonance Research Platform*`

    const filename = `analysis-${analysis.rubric.title.replace(/[^a-z0-9]/gi, '-').substring(0, 30)}-${new Date().toISOString().split('T')[0]}.md`

    return new NextResponse(markdown, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    console.error('Export error:', error)
    return NextResponse.json({ error: 'Failed to export' }, { status: 500 })
  }
}
